name: Build and Setup

on:
  push:
    branches:
      - main

jobs:
  build-and-setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Set up Maven
        run: |
          sudo apt-get install -y maven
          export M2_HOME=/usr/share/maven
          export PATH=${M2_HOME}/bin:${PATH}

      - name: Clean
        run: |
          cd src/front
          mvn clean

      - name: Install
        run: |
          cd src/front
          mvn install

      - name: Setup Virtual Environment
        run: |
          cd src/back
          if ! command -v python3 &> /dev/null; then
            curl -O https://www.python.org/ftp/python/3.9.0/Python-3.9.0.tgz
            tar -xzvf Python-3.9.0.tgz
            cd Python-3.9.0
            ./configure && make && sudo make install
            export PYTHON3_PATH=/usr/local/bin/python3
          else
            export PYTHON3_PATH=$(which python3)
          fi
          ${PYTHON3_PATH} -m venv venv
          source venv/bin/activate && pip install -r requirements.txt
